#4 TO - DO - Task
Please complete all the problem listed below.
4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
#1. Creating an empty array with size 2x2
empty_arr=np.empty((2,2))
print("Empty array: ",empty_arr)

#2. Creating an all one array with size 4x2
one_arr=np.ones((4,2))
print("All one array: ",one_arr)

#3. Creating a new array of given shape and type,filled with fill value
fill_arr=np.full((2,2),7)
print("Array filled with fill value: ",fill_arr)

#4. Creating a new array of zeros with same shape and type as a given array
given_array=np.array([[1,2,3],[4,5,6]])
zeros_array=np.zeros_like(given_array)
print("Array of zeros with same shape and type as a given array: ",zeros_array)

#5. Creating a new array of ones with same shape and type as a given array
ones_array=np.ones_like(given_array)
print("Array of ones with same shape and type as a given array: ",ones_array)

#6. Converting an existing list to a numpy array
new_list=[1,2,3,4]
list_to_array=np.array(new_list)
print("List converted to array: ",list_to_array)





Empty array:  [[4.94806921e-310 0.00000000e+000]
 [1.33511018e-306 1.33511562e-306]]
All one array:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array filled with fill value:  [[7 7]
 [7 7]]
Array of zeros with same shape and type as a given array:  [[0 0 0]
 [0 0 0]]
Array of ones with same shape and type as a given array:  [[1 1 1]
 [1 1 1]]
List converted to array:  [1 2 3 4]


#4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [5]:
import numpy as np

#1. Creating an array with values ranging from 10 to 49
arr=np.arange(10,50)
print("Array with values ranging from 10 to 49: ",arr)

#2. Creating a 3x3 matrix with values ranging from 0 to 8
x=np.arange(0,9).reshape((3,3))
print("3x3 matix with values ranging from 0 to 8: ",x)

#3. Creating a 3x3 identity matrix
i=np.eye(3,3)
print("Identity matrix of 3x3: ",i)

#4. Creating a ranodm array of size 30 and finding the mean of the array
random_arr=np.random.random(30)
mean=random_arr.mean()
print("Mean of the array: ",mean)

#5. Creating a 10x10 array with random values and finding the minimum and maximum values
array=np.random.random((10,10))
min_value=array.min()
max_value=array.max()
print("Minimum value= ",min_value," and Maximum value= ",max_value)

#6. Creating a zero array of size 10 and replacing 5th element with 1.
zero_arr=np.zeros(10)
zero_arr[4]=1
print("Zero array with 1 as its 5th element: ",zero_arr)

#7. Reversing an array
arr = [1,2,0,0,4,0]
reversed_arr=np.array(arr)[::-1]
print("Reversed array: ",reversed_arr)

#8. Creating a 2d array with 1 on border and 0 inside.
array=np.zeros((2,2))
print("Original array: ",array)
bordered_array=np.pad(array,pad_width=1,mode='constant',constant_values=1)
print("Array with 1 on border and 0 inside: ",bordered_array)

#9. Creating a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard_arr = np.indices((8, 8)).sum(axis=0) % 2
print("Checkerboard_arr: \n", checkerboard_arr)

Array with values ranging from 10 to 49:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 matix with values ranging from 0 to 8:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity matrix of 3x3:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of the array:  0.501475116916289
Minimum value=  1.3861520179458964e-05  and Maximum value=  0.9951708386649198
Zero array with 1 as its 5th element:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed array:  [0 4 0 0 2 1]
Original array:  [[0. 0.]
 [0. 0.]]
Array with 1 on border and 0 inside:  [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
Checkerboard_arr: 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

#Provided arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1. Adding array x and y
array_sum=np.add(x,y)
print("The result after adding arrays x and y: ",array_sum)

#2. Subtracting array w from v
array_subtract=np.subtract(v,w)
print("The result after subtracting w from v: ",array_subtract)

#3. Multiplying array x with 3
array_multiply=x*3
print("The result after multiplying x with 3: ",array_multiply)

#4. Finding square of each element of the array y
array_square=y*y
print("The result obtained by finding square of each element of the array y: ",array_square)

#5. Finding dot product
v_w=np.dot(v,w)
x_v=np.dot(x,v)
x_y=np.dot(x,y)
print("Dot product of v and w: ",v_w)
print("Dot product of x and v: ",x_v)
print("Dot product of x and y: ",x_y)

#6. Concatenating x(and)y along row and Concatenating v(and)w along column.
concat_x_y=np.concatenate((x,y),axis=0) #or np.vstack((x,y))
concat_v_w=np.concatenate((x,y),axis=1) #or np.hstack((v,w))
print("Concatenating x and y along row= ",concat_x_y)
print("Concatenating v and w along column= ",concat_v_w)

#7. Concatenating x(and)v
#concat_x_v=np.concatenate((x,v),axis=0) We observe ValueError in this particular line beacuse both the arrays have different dimensions

The result after adding arrays x and y:  [[ 6  8]
 [10 13]]
The result after subtracting w from v:  [-2 -2]
The result after multiplying x with 3:  [[ 3  6]
 [ 9 15]]
The result obtained by finding square of each element of the array y:  [[25 36]
 [49 64]]
Dot product of v and w:  219
Dot product of x and v:  [29 77]
Dot product of x and y:  [[19 22]
 [50 58]]
Concatenating x and y along row=  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenating v and w along column=  [[1 2 5 6]
 [3 5 7 8]]


#Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

#Provided Arrays
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#Finding inverse of A
A_inverse=np.linalg.inv(A)

#1.
#Calculating A.A-1
A_and_Ainverse=np.dot(A,A_inverse)
print("A.A-1= ",A_and_Ainverse)

#Finding identity matrix
identity_matrix=np.eye(2,2)
print("Identity matrix= ",identity_matrix)

if(np.allclose(A_and_Ainverse,identity_matrix)):
  print("Comparing the results, the elements in A.A-1 are equal or close to equal with the identity matrix. Therefore, A.A-1=I")
else:
  print("A.A-1 ̸= I")

#2.
#Calculating AB
AB=np.matmul(A,B)
print("AB= ",AB)
#Calculating BA
BA=np.matmul(B,A)
print("BA= ",BA)
if(np.array_equal(AB,BA)):
  print("The result obtained by observing AB and BA is that AB=BA")
else:
  print("This proves the matrix multiplication is not commutative. Therefore, AB ̸= BA.")

#3.
#Calculating transverse of AB
AB_transverse=AB.T
print("The transverse of AB= ",AB_transverse)
#Calculating Transverse of B and A and multiplying them
A_transverse=A.T
B_transverse=B.T
Btransverse_Atransverse=np.matmul(B_transverse,A_transverse)
print("BT.AT= ",Btransverse_Atransverse)
if(np.array_equal(AB_transverse,Btransverse_Atransverse)):
  print("From the obtained results, we can observe that (AB)T=BT.AT")
else:
  print("From the obtained results, we can observe that (AB)T ̸= BT.AT")

#4.
A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
#Calculating inverse of A
A_inverse=np.linalg.inv(A)
#Multiplying the inverse with B
A_inverse_and_B=np.matmul(A_inverse,B)
print("The value of X= ",A_inverse_and_B)


A.A-1=  [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix=  [[1. 0.]
 [0. 1.]]
Comparing the results, the elements in A.A-1 are equal or close to equal with the identity matrix. Therefore, A.A-1=I
AB=  [[23 13]
 [51 29]]
BA=  [[36 44]
 [13 16]]
This proves the matrix multiplication is not commutative. Therefore, AB ̸= BA.
The transverse of AB=  [[23 51]
 [13 29]]
BT.AT=  [[23 51]
 [13 29]]
From the obtained results, we can observe that (AB)T=BT.AT
The value of X=  [ 2.  1. -2.]


#4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [4]:
import numpy as np
import random
from timeit import timeit
#Generating a larger random sample data
size=1000000
#Python lists
Z1_list=random.sample(range(size+1),size)
Z2_list=random.sample(range(size+1),size)
#Numpy arrays
Z1_arr=np.array(Z1_list)
Z2_arr=np.array(Z2_list)

#1. Element-wise addition
def add_python(a,b):
  return [A+B for A,B in zip(a,b)]
def add_numpy(a,b):
  return np.add(a,b)
#Calculating the execution of each function
python_addtime = timeit("add_python(Z1_list,Z2_list)", globals=globals(), number=100)
numpy_addtime = timeit("add_numpy (Z1_arr,Z2_arr)", globals=globals(), number=100)
print(f"Pure Python addition:{python_addtime:.6f} seconds per loop")
print(f"Numpy addition:{numpy_addtime:.6f} seconds per loop")

#2. Element-wise multiplication
def multiply_python(a,b):
  return [A*B for A,B in zip(a,b)]
def multiply_numpy(a,b):
  return a*b
#Calculating the execution of each function
python_multiplytime = timeit("multiply_python(Z1_list,Z2_list)", globals=globals(), number=100)
numpy_multiplytime = timeit("multiply_numpy (Z1_arr,Z2_arr)", globals=globals(), number=100)
print(f"Pure Python multiplication:{python_multiplytime:.6f} seconds per loop")
print(f"Numpy multiplication:{numpy_multiplytime:.6f} seconds per loop")

#3.Dot product
def dot_python(a,b):
  return sum([A*B for A,B in zip(a,b)])
def dot_numpy(a,b):
  return np.dot(a,b)
#Calculating the execution of each function
python_dottime = timeit("dot_python(Z1_list,Z2_list)", globals=globals(), number=100)
numpy_dottime = timeit("dot_numpy(Z1_arr,Z2_arr)", globals=globals(), number=100)
print(f"Pure Python dot product:{python_dottime:.6f} seconds per loop")
print(f"Numpy dot product:{numpy_dottime:.6f} seconds per loop")


# 4. Matrix Multiplication
# Reshape into 2D arrays (e.g., 300 x 300 matrices)
matrix_size =300 # Adjust as needed
Z1_matrix_list = [Z1_list[i:i + matrix_size] for i in range(0, matrix_size ** 2, matrix_size)]
Z2_matrix_list = [Z2_list[i:i + matrix_size] for i in range(0, matrix_size ** 2, matrix_size)]

Z1_matrix_arr = np.array(Z1_matrix_list)
Z2_matrix_arr = np.array(Z2_matrix_list)

def matrix_python(a, b):
    return [
        [sum(A * B for A, B in zip(row_a, col_b)) for col_b in zip(*b)]
        for row_a in a
    ]

def matrix_numpy(a, b):
    return np.matmul(a, b)

# Calculating the execution of each function
python_matrix_time = timeit("matrix_python(Z1_matrix_list, Z2_matrix_list)", globals=globals(), number=10)
numpy_matrix_time = timeit("matrix_numpy(Z1_matrix_arr, Z2_matrix_arr)", globals=globals(), number=10)

print(f"Pure Python matrix multiplication: {python_matrix_time:.6f} seconds per loop")
print(f"NumPy matrix multiplication: {numpy_matrix_time:.6f} seconds per loop")

Pure Python addition:31.850219 seconds per loop
Numpy addition:0.106566 seconds per loop
Pure Python multiplication:31.460400 seconds per loop
Numpy multiplication:0.116472 seconds per loop
Pure Python dot product:33.634967 seconds per loop
Numpy dot product:0.085685 seconds per loop
Pure Python matrix multiplication: 53.124960 seconds per loop
NumPy matrix multiplication: 0.247118 seconds per loop
